additionalArguments:
    - --serverstransport.insecureskipverify=true
    - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
    - --certificatesresolvers.cloudflare.acme.email=<your-acme-mail>
    - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
    - --certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme-cloudflare.json
logs:
    general:
        level: ERROR

ports:
    web:
        redirectTo: websecure
    websecure:
        tls:
            enabled: true
            certResolver: cloudflare

env:
    - name: CF_API_EMAIL
      valueFrom:
          secretKeyRef:
              key: email
              name: cloudflare-credentials
    - name: CF_API_KEY
      valueFrom:
          secretKeyRef:
              key: apiKey
              name: cloudflare-credentials

# Disable Dashboard
ingressRoute:
    dashboard:
        enabled: false

# Persistent Storage
persistence:
    enabled: true
    name: ssl-certs
    size: 1Gi
    path: /ssl-certs

deployment:
    initContainers:
    - name: volume-permissions
      image: busybox:1.35.0
      command: ["sh", "-c", "chmod -Rv 600 /ssl-certs/* || true"]
      volumeMounts:
      - name: ssl-certs
        mountPath: /ssl-certs

# Set Traefik as your default Ingress Controller, according to Kubernetes 1.19+ changes.
ingressClass:
    enabled: true
    isDefaultClass: true
